# data.terraform_remote_state.vpc / .alb are generated by env.hcl's remote_state_data
# generate block (see prod/env.hcl's remote_state_deps) — not hand-written here.
module "api_gateway" {
  source = "../../modules/api-gateway"

  private_subnet_ids    = data.terraform_remote_state.vpc.outputs.private_subnet_ids
  alb_security_group_id = data.terraform_remote_state.alb.outputs.alb_security_group_id
  alb_listener_arn      = data.terraform_remote_state.alb.outputs.listener_arn
}
