# data.terraform_remote_state.vpc / .k8s_nodes are generated by env.hcl's remote_state_data
# generate block (see prod/env.hcl's remote_state_deps) — not hand-written here.
module "rds" {
  source = "../../modules/rds"

  vpc_id                 = data.terraform_remote_state.vpc.outputs.vpc_id
  private_subnet_ids     = data.terraform_remote_state.vpc.outputs.private_subnet_ids
  node_security_group_id = data.terraform_remote_state.k8s_nodes.outputs.node_security_group_id
}
