# data.terraform_remote_state.vpc is generated by env.hcl's remote_state_data generate
# block (see prod/env.hcl's remote_state_deps) — not hand-written here.
module "k8s_nodes" {
  source = "../../modules/k8s-nodes"

  vpc_id             = data.terraform_remote_state.vpc.outputs.vpc_id
  vpc_cidr           = data.terraform_remote_state.vpc.outputs.vpc_cidr
  private_subnet_ids = data.terraform_remote_state.vpc.outputs.private_subnet_ids
}
