{{- if not .Values.db.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contacts-micro-service.secretName" . }}
  labels:
    {{- include "contacts-micro-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  DB_USERNAME: {{ .Values.db.username | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
{{- end }}
