apiVersion: v1
kind: Service
metadata:
  name: {{ include "contacts-micro-service.name" . }}
  labels:
    {{- include "contacts-micro-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "contacts-micro-service.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
